### ISSUE TITLE
`$t` does not have TypeScript auto-completions

### ISSUE THREAD

**Issue by innocenzi** [intlify/vue-i18n#1215]
### Reporting a bug?

The `$t` global function in SFCs' templates don't seem to support global TypeScript definitions.

![CleanShot 2022-11-05 at 23 02 35](https://user-images.githubusercontent.com/16060559/200142987-a1115247-4dbf-4d44-ab54-10f7a7fdb732.png)

The [documentation](https://vue-i18n.intlify.dev/guide/advanced/typescript.html#global-resource-schema-type-definition) regarding this topic doesn't mention `$t` but its definition look like it should support auto-completion.

### Expected behavior

`$t` should provide auto-completion through the overriden `DefineLocaleMessage` interface, like `t` exported from `useI18n` does.

![CleanShot 2022-11-05 at 23 03 33](https://user-images.githubusercontent.com/16060559/200143037-bca4a350-ae87-4b89-94a5-bed5650ccb0b.png)

### Reproduction

Create a `i18n.json` file with the following content: 

<details>
<summary>Details</summary>

```json
{
	"en": {
		"login": {
			"welcome_text_title": "Welcome back!",
			"welcome_text_help_text": "Enter your credentials to access the app.",
			"email_field_placeholder": "Enter your email",
			"password_field_placeholder": "Enter your password",
			"sign_in_button_label": "Sign in",
			"quick_login_cta_text": "Wanna login quickly?",
			"quick_login_link_text": "Click here."
		}
	}
}

```

</details>

Create a `i18n.ts` file with the following content:

```ts
import { createI18n } from 'vue-i18n'
import messages from './i18n.json'

export type MessageSchema = typeof messages['en']

declare module 'vue-i18n' {
	export interface DefineLocaleMessage extends MessageSchema {}
}

const i18n = createI18n<[MessageSchema], 'en'>({
	locale: 'en',
	inheritLocale: true,
	messages,
})

export default i18n
```

Create a Vue 3 application, import `./i18n.ts` and register the exported plugin.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 106.0.5
    Safari: 16.0
  npmPackages:
    @vitejs/plugin-vue: ^3.2.0 => 3.2.0 
    @vue/runtime-core: ^3.2.41 => 3.2.41 
    vite: ^3.2.2 => 3.2.2 
    vite-plugin-run: ^0.2.0 => 0.2.0 
    vue: ^3.2.41 => 3.2.41 
    vue-i18n: ^9.0.0 => 9.2.2
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/vue-i18n-next/discussions)
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TheVaan** [comment]
Any news about `$t` having TypeScript autocomplete?

**Comment by wJoenn** [comment]
In the meantime you can use the non-global method and you'll have all the intellisense you need, just like in the script

```html
<template>
  <div>{{ t("foo") }}</div>
</template>

<script setup lang="ts">
  const { t } = useI18n()
</script>
```

**Comment by beqacrc** [comment]
Any updates?

**Comment by mitjans** [comment]
I was looking for this feature, is there any update on this?

I am open to contributing!

**Comment by mitjans** [comment]
When declaring types for `$t` in `packages/vue-i18n/src/vue.d.ts`, there's this parameter type `Path` added:

```ts
$t<...>(
  key: Key | ResourceKeys | Path
): TranslateResult
```

The definition of this type `Path` comes from `packages/core-base/src/resolver.ts` and is:

```ts
/** @VueI18nGeneral */
export type Path = string```

This is breaking type inference for translations when using `$t`. I've tried to remove `| Path` from all `$t` declarations and it works!

**Comment by kazupon** [comment]
close via #1883 1883
