### ISSUE TITLE
Getting 'Cannot read properties of undefined (reading 't')' error in core-base.mjs::formatParts

### ISSUE THREAD

**Issue by LZTWilliam** [intlify/vue-i18n#1805]
### Reporting a bug?

After upgrading vue-i18n from 9.2.2 to 9.10.1, and run my application in production mode, I get error while calling i18n.t API as below.
```javascript
import i18n from 'somewhere createI18n'
i18n.global.t('my_i18n_key')
```
![image](https://github.com/intlify/vue-i18n-next/assets/17825701/740af45f-870d-4c75-a55e-d8075942f752)

For now, I locating the difference between the scenario is in the function messageCompiler in core-base.mjs.

1. Before upgrading
`messageCompiler` returns ```new Function(`return ${code}`)()``` which directly returns my translated message (which is a plain string)
![image](https://github.com/intlify/vue-i18n-next/assets/17825701/87e58f86-9d2e-41c1-abf9-c56fbc4a7ebe)

2. After upgrading, dev mode
`messageCompiler` returns `() => message` which also returns translated message directly
![image](https://github.com/intlify/vue-i18n-next/assets/17825701/bffa7c19-239f-4851-ad1f-4850ec410400)

3. After upgrading, production mode
`messageCompiler` returns `format(message)` which leads to `(ctx) => formatParts(ctx, ast)`. And when formatParts is invoked, the parameter `ast` is just my message string, which cause the error report.
![image](https://github.com/intlify/vue-i18n-next/assets/17825701/f65a7675-cfce-4f1c-bc1e-3a75937ad375)

Is this the expected behavior? Or should I do some other configuration to allow my plain text is properly translated?

### Expected behavior

No error occurs

### Reproduction

Still trying. No nuxt, no SSR in my case

### System Info

```shell
System:                                                
    OS: Windows 10 10.0.19045                            
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 6.47 GB / 31.84 GB                           
  Binaries:                                              
    Node: 18.14.1 - D:\Program Files\nodejs\node.EXE     
    npm: 8.19.4 - D:\Program Files\nodejs\npm.CMD        
  Browsers:                                              
    Chrome: 122.0.6261.129
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.19041.3636
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n-next/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n-next/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n-next/discussions)

**Comment by LZTWilliam** [comment]
While working on minimal production I find wierd thing. The message compiler registration is different between `vue-i18n.cjs` and `vue-i18n.mjs`
```javascript
// vue-i18n.mjs
// register message compiler at vue-i18n
if (__INTLIFY_JIT_COMPILATION__) {
    registerMessageCompiler(compile);
}
else {
    registerMessageCompiler(compileToFunction);
}

// vue-i18n.cjs
// register message compiler at vue-i18n
{
    coreBase.registerMessageCompiler(coreBase.compile);
}
```
In my minimal reproduction project the mjs file is invoked, and run `registerMessageCompiler(compileToFunction);`, everything alright.
In my production project the cjs file is invoked(maybe because of babel?), the compiler is different from the one registered in mjs.

Shouldn't the code be same in mjs and cjs? Does the cjs lack the `(__INTLIFY_JIT_COMPILATION__)` branch? Looking for reply, thx.

**Comment by kazupon** [comment]
Thank you for your reporting!

> [Just require the vue-i18n.cjs can reproduct this issue](https://stackblitz.com/edit/vitejs-vite-hq7qgy?file=src%2Fmain.js)

I think that you don't setup `@intlify/unplugin-vue-i18n`
You can setup with it.
https://vue-i18n.intlify.dev/guide/advanced/sfc.html#configure-plugin-for-webpack

your project uses Vue CLI, this documentation will be helpful.
https://cli.vuejs.org/guide/webpack.html#simple-configuration

**Comment by LZTWilliam** [comment]
Finally found an alias resolving setting in my `vue.config.js`. Not sure why.
```js
'vue-i18n': 'vue-i18n/dist/vue-i18n.cjs.js',
```
Remove this line and my project works fine.
Thanks again for your reply!!
