### ISSUE TITLE
Cloudflare miniflare dev error

### ISSUE THREAD

**Issue by simultsop** [intlify/vue-i18n#1902]
### Reporting a bug?

When attempting to make use of useI18n on a cloudflare wrangler environment there is an error thrown. Removing i18n use composable, the SPA serves without a problem.

### Expected behavior

Run properly

### Reproduction

Clone this repo https://github.com/gmesml/i18n-cf-pages, after npm install, run the project using 2 terminal instances, one would keep vite building and watching for changes with: ```npm run dev```. The other one served by cloudflare wrangler: ```npm run pages:dev```

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 67.56 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    npm: 10.8.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
  npmPackages:
    @vitejs/plugin-vue: ^5.0.5 => 5.0.5 
    @vue/tsconfig: ^0.5.1 => 0.5.1 
    vite: ^5.3.1 => 5.3.4 
    vue: ^3.4.29 => 3.4.31 
    vue-i18n: ^9.13.1 => 9.13.1 
    vue-router: ^4.3.3 => 4.4.0 
    vue-tsc: ^2.0.21 => 2.0.26
```

### Screenshot

<img width="626" alt="Screenshot at Jul 22 19-21-56" src="https://github.com/user-attachments/assets/2a2630ee-2a9d-45fb-847b-66e33adffcb8">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)

**Comment by gmesml** [comment]
Having added: ```allowComposition: true```  on ```createI18n({allowComposition: true})``` allows us to use i18n composable. 

@kazupon don't you think this should default to true?
