### ISSUE TITLE
Fallback locale not working with linked messages

### ISSUE THREAD

**Issue by mdoesburg** [intlify/vue-i18n#1912]
### Reporting a bug?

When using a linked message, the linked message does not resolve.

### Expected behavior

I expect the linked message to be resolved from the fallback locale.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-uwlppf?file=src%2Fmain.ts

1. Go to the reproduction
2. Switch to the `en-variant` locale
3. See `No found` instead of `No apples found`

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 77.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.6.0 - ~/Library/pnpm/pnpm
    Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.99
    Edge: 127.0.2651.86
    Safari: 17.6
  npmPackages:
    @intlify/unplugin-vue-i18n: 4.0.0 => 4.0.0 
    @vitejs/plugin-vue: ^5.1.2 => 5.1.2 
    @vue/eslint-config-prettier: ^9.0.0 => 9.0.0 
    @vue/eslint-config-typescript: ^13.0.0 => 13.0.0 
    @vue/test-utils: ^2.4.6 => 2.4.6 
    @vue/tsconfig: ^0.5.1 => 0.5.1 
    vite: ^5.3.5 => 5.3.5 
    vite-plugin-graphql-codegen: ^3.3.8 => 3.3.8 
    vite-plugin-vuetify: 2.0.4 => 2.0.4 
    vitest: ^2.0.5 => 2.0.5 
    vitest-canvas-mock: ^0.3.3 => 0.3.3 
    vue: 3.4.35 => 3.4.35 
    vue-component-type-helpers: 2.0.29 => 2.0.29 
    vue-content-loader: ^2.0.1 => 2.0.1 
    vue-echarts: 6.6.9 => 6.6.9 
    vue-i18n: 9.13.1 => 9.13.1 
    vue-router: ^4.4.2 => 4.4.2 
    vue-tsc: 2.0.29 => 2.0.29 
    vue3-perfect-scrollbar: ^2.0.0 => 2.0.0 
    vuetify: 3.6.14 => 3.6.14
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)

**Comment by mdoesburg** [comment]
@kazupon First off, thanks for all the great work you do! If you have a moment, could you please take a look at this? It seems slightly similar to this old issue that was already resolved: https://github.com/intlify/vue-i18n/issues/933

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!
Sorry, my late response.

I've checked your reproduction.
I'll try to fix this issue.

Thank you!
