### ISSUE TITLE
Should change '@vue/runtime-core' to 'vue'

### ISSUE THREAD

**Issue by sunxi1997** [intlify/vue-i18n#1915]
### Reporting a bug?

vue-i18n@latest is no longer compatible with vue-router@latest

### Expected behavior

vue-i18n should replaces `declare module '@vue/runtime-core'` with `declare module 'vue'` [like it's supposed to be](https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties). If you are also augmenting `@vue/runtime-core`, you will likely have to change it to `vue`. 

[What did vue-router do](https://github.com/vuejs/router/pull/2295/files)

### Reproduction

Problem Like This
![屏幕录制 2024-08-13 095606](https://github.com/user-attachments/assets/9a4b61ce-05f9-40e9-b9c7-0d11dda52a23)

### System Info

```shell
{
  "name": "demo",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "preview": "vite preview",
    "build-only": "vite build",
    "type-check": "vue-tsc --build --force"
  },
  "dependencies": {
    "vue": "^3.4.29",
    "vue-i18n": "^9.13.1",
    "vue-router": "^4.4.3"
  },
  "devDependencies": {
    "@tsconfig/node20": "^20.1.4",
    "@types/node": "^20.14.5",
    "@vitejs/plugin-vue": "^5.0.5",
    "@vue/tsconfig": "^0.5.1",
    "typescript": "~5.4.0",
    "vite": "^5.3.1",
    "vue-tsc": "^2.0.21"
  }
}
```

### Screenshot

![image](https://github.com/user-attachments/assets/8c924041-8f1c-4ce6-9773-8222cfb956c2)
![image](https://github.com/user-attachments/assets/cf451917-575c-4a41-8a14-aa363754c9fc)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!

I've already fixed at below PR
https://github.com/intlify/vue-i18n/pull/1888

You can try to use v10 beta
