### ISSUE TITLE
Hierarchical locale messages under petite-vue-i18n are not working

### ISSUE THREAD

**Issue by maxfrees** [intlify/vue-i18n#1965]
### Reporting a bug?

Hierarchical locale messages under petite-vue-i18n are not working

### Expected behavior

Hierarchical locale messages under petite-vue-i18n are not working

### Reproduction

https://stackblitz.com/edit/vitejs-vite-gy19pc?file=src%2Fmain.ts

ref https://github.com/intlify/vue-i18n/issues/1962

### System Info

```shell
windows
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)

**Comment by kazupon** [comment]
Thank you for your reporting!

I've just fixed this issue.
You can try to install vue-i18n v10.0.3
and You need to install `@intlify/unplugin-vue-i18n` v5.2 and `module` option setting
See the docs
https://vue-i18n.intlify.dev/guide/advanced/lite#setting-bundler-plugin

**Comment by maxfrees** [comment]
It will probably be a lot less than vue-i18n, because  petite-vue-i18n need to  install @intlify/unplugin-vue-i18n and @intlify/core separately, we need to evaluate it

**Comment by maxfrees** [comment]
Now it looks a bit cumbersome, in addition to the need to install petite-vue-i18n, you also need @intlify/unplugin-vue-i18n and @intlify/core-base

**Comment by kazupon** [comment]
close
We believe this issue has been resolved.
If you have still an issue, please open a new one.

Thanks!
