### ISSUE TITLE
After using @intlify/unplugin-vue-i18n  vue-i18n cannot be used normally ?

### ISSUE THREAD

**Issue by wjp980108** [intlify/vue-i18n#1979]
### Reporting a bug?

After using @intlify/unplugin-vue-i18n vue-i18n cannot use the console to report an error normally

### Expected behavior

Page normal display content

### Reproduction

https://stackblitz.com/edit/vue-i18n-get-started-izpy9f?file=App.vue

### System Info

```shell
System:
    OS: windows
Binaries:
    Node: 20.17.0 
    npm: 10.8.2
Browsers:
    Chrome: 129.0.6668.70
```

### Screenshot

![image](https://github.com/user-attachments/assets/52d47ebe-1201-4e85-8367-604594a0f8a2)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)

**Comment by Wick96** [comment]
After updating @intlify/unplugin-vue-i18n from 4.0.0 to v 5.2.0, I had the same issue. Vue i18n is 9.14.1.

I reverted it to 4.0.0, which works as it should.

**Comment by wjp980108** [comment]
> After updating @intlify/unplugin-vue-i18n from 4.0.0 to v 5.2.0, I had the same issue. Vue i18n is 9.14.1.
> 
> I reverted it to 4.0.0, which works as it should.

Thank you for your reply, I'll try it

**Comment by theolvx-wfn** [comment]
I had the same issue!

**Comment by wjp980108** [comment]
> I had the same issue!
You can only reduce the version use first.

**Comment by kazupon** [comment]
Thank you for your reporting!

I've checked your reporoduction.
`@intlify/unplugin-vue-i18n` v5.2.0 has used in your reproduction
That version require the vue-i18n v10 or later.
Please upgrade your vue-i18n v10!

Thanks!
