### ISSUE TITLE
Plural behavior with count == 0

### ISSUE THREAD

**Issue by H3llK33p3r** [intlify/vue-i18n#1982]
### Reporting a bug?

Using the example in the documentation with 'car' and 'apple'  : https://vue-i18n.intlify.dev/guide/essentials/pluralization.html
There is a strange behavior with car when the second argument is 0 (count). Plural is used instead of singular.

The default plural rule with the first ternary operation is bugged if we provide 0 ! 

```
function pluralDefault(choice, choicesLength) {
    choice = Math.abs(choice);
    if (choicesLength === 2) {
        // prettier-ignore
        return choice
            ? choice > 1
                ? 1
                : 0
            : 1;
    }
    return choice ? Math.min(choice, 2) : 0;
}
```

### Expected behavior

For count from 0 to 1, singular must be used ? 

### Reproduction

Here a sample of the issue : https://stackblitz.com/edit/vitejs-vite-vow5pz?file=src%2FApp.vue

### System Info

```shell
WSL / Ubuntu / "vue-i18n": "^9.2.2"
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)

**Comment by BobbieGoede** [comment]
This looks like it is working as intended to me, only 1 can be singular, anything more or less is not singular. 

Your example actually demonstrates this well
* zero cars (or) no cars
* zero apples (or) no apples

Using singular for zero amounts would be grammatically incorrect, this probably differs across languages.

**Comment by H3llK33p3r** [comment]
`Using singular for zero amounts would be grammatically incorrect, this probably differs across languages.`

Ok I understand, both can be used depending on the context. It's strange, as a French, to see plural with a 0 quantity ! 
Thank you for your response.
