### ISSUE TITLE
uniapp 中使用 vue- i18n 报错

### ISSUE THREAD

**Issue by PMAT77** [intlify/vue-i18n#2052]
### Reporting a bug?

Uncaught SyntaxError: The requested module '/node_modules/@intlify/shared/dist/shared.esm-bundler.js?v=fa5fe2ac' does not provide an export named 'join' (at message-compiler.mjs:6:1)

<img width="265" alt="image" src="https://github.com/user-attachments/assets/3083b8b9-d72d-4b99-ba40-ca9f29f3fd0d" />

### Expected behavior

Uncaught SyntaxError: The requested module '/node_modules/@intlify/shared/dist/shared.esm-bundler.js?v=fa5fe2ac' does not provide an export named 'join' (at message-compiler.mjs:6:1)

<img width="265" alt="image" src="https://github.com/user-attachments/assets/3083b8b9-d72d-4b99-ba40-ca9f29f3fd0d" />

### Reproduction

Uncaught SyntaxError: The requested module '/node_modules/@intlify/shared/dist/shared.esm-bundler.js?v=fa5fe2ac' does not provide an export named 'join' (at message-compiler.mjs:6:1)

<img width="265" alt="image" src="https://github.com/user-attachments/assets/3083b8b9-d72d-4b99-ba40-ca9f29f3fd0d" />

### System Info

```shell
Uncaught SyntaxError: The requested module '/node_modules/@intlify/shared/dist/shared.esm-bundler.js?v=fa5fe2ac' does not provide an export named 'join' (at message-compiler.mjs:6:1)

<img width="265" alt="image" src="https://github.com/user-attachments/assets/3083b8b9-d72d-4b99-ba40-ca9f29f3fd0d" />
```

### Screenshot

<img width="639" alt="image" src="https://github.com/user-attachments/assets/d4e4f75c-fab4-4841-aed0-b381e42a74a1" />

<img width="546" alt="image" src="https://github.com/user-attachments/assets/78507ade-ca09-4d33-b4bc-3bb648e8e757" />

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)

**Comment by chenbimo** [comment]
same.

**Comment by RanMaoting** [comment]
same.

**Comment by JinPengGeng** [comment]
same

**Comment by maoyanfei** [comment]
版本问题，这个版本没有错误{"vue": "^3.5.13", "vue-i18n": "9.1.9"}
