### ISSUE TITLE
[intlify] 'v-t' has been deprecated in v11. Use translate APIs ('t' or '$t') instead with v11

### ISSUE THREAD

**Issue by pzgz** [intlify/vue-i18n#2056]
### Reporting a bug?

After upgraded to v11, getting following warning in console, event `v-t` was not used, checked source codes, looks like there's no way to disable this output. Maybe an option to opt-out the directive registration?

> [intlify] 'v-t' has been deprecated in v11. Use translate APIs ('t' or '$t') instead with v11

### Expected behavior

A way to bypass the warning in console for disturbing or disable the `v-t` registration before it's removed.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-7mewe8xx?file=package.json

### System Info

```shell
macOS 15.3
vuye 3.5.13
```

### Screenshot

![CleanShot 2024-12-25 at 17 40 51@2x](https://github.com/user-attachments/assets/ef748a1f-f913-47fd-8059-698e4ce79032)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)

**Comment by oleynikyurij** [comment]
similar problem, intlify/unplugin-vue-i18n: 6.0.2, vue-i18n: 11.0.0, nuxt: 3.15.0  
`import { createI18n } from 'vue-i18n'
import en from '../locale/en.json'
import de from '../locale/de.json'
import uk from '../locale/uk.json'

export default defineNuxtPlugin(({ vueApp }) => {
    const i18n = createI18n({
        legacy: false,
        globalInjection: true,
        locale: 'uk',
        messages: {
            en, uk, de
        }
    })
    vueApp.use(i18n)
})`
